# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_communication/proto/proto_test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_communication/proto/proto_test.proto',
  package='demo',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n grpc_communication/proto/proto_test.proto\x12\x04\x64\x65mo\")\n\x0c\x64\x65mo_request\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"-\n\ndemo_reply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06salary\x18\x02 \x01(\x05\x32;\n\x04\x44\x65mo\x12\x33\n\tdemo_func\x12\x12.demo.demo_request\x1a\x10.demo.demo_reply\"\x00\x62\x06proto3'
)




_DEMO_REQUEST = _descriptor.Descriptor(
  name='demo_request',
  full_name='demo.demo_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='demo.demo_request.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='demo.demo_request.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=83,
)


_DEMO_REPLY = _descriptor.Descriptor(
  name='demo_reply',
  full_name='demo.demo_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='demo.demo_reply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='salary', full_name='demo.demo_reply.salary', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['demo_request'] = _DEMO_REQUEST
DESCRIPTOR.message_types_by_name['demo_reply'] = _DEMO_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

demo_request = _reflection.GeneratedProtocolMessageType('demo_request', (_message.Message,), {
  'DESCRIPTOR' : _DEMO_REQUEST,
  '__module__' : 'grpc_communication.proto.proto_test_pb2'
  # @@protoc_insertion_point(class_scope:demo.demo_request)
  })
_sym_db.RegisterMessage(demo_request)

demo_reply = _reflection.GeneratedProtocolMessageType('demo_reply', (_message.Message,), {
  'DESCRIPTOR' : _DEMO_REPLY,
  '__module__' : 'grpc_communication.proto.proto_test_pb2'
  # @@protoc_insertion_point(class_scope:demo.demo_reply)
  })
_sym_db.RegisterMessage(demo_reply)



_DEMO = _descriptor.ServiceDescriptor(
  name='Demo',
  full_name='demo.Demo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=132,
  serialized_end=191,
  methods=[
  _descriptor.MethodDescriptor(
    name='demo_func',
    full_name='demo.Demo.demo_func',
    index=0,
    containing_service=None,
    input_type=_DEMO_REQUEST,
    output_type=_DEMO_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEMO)

DESCRIPTOR.services_by_name['Demo'] = _DEMO

# @@protoc_insertion_point(module_scope)
