# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_communication.proto import proto_test_pb2 as grpc__test_dot_proto_dot_proto__test__pb2


class DemoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.demo_func = channel.unary_unary(
                '/demo.Demo/demo_func',
                request_serializer=grpc__test_dot_proto_dot_proto__test__pb2.demo_request.SerializeToString,
                response_deserializer=grpc__test_dot_proto_dot_proto__test__pb2.demo_reply.FromString,
                )


class DemoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def demo_func(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DemoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'demo_func': grpc.unary_unary_rpc_method_handler(
                    servicer.demo_func,
                    request_deserializer=grpc__test_dot_proto_dot_proto__test__pb2.demo_request.FromString,
                    response_serializer=grpc__test_dot_proto_dot_proto__test__pb2.demo_reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.Demo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Demo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def demo_func(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/demo.Demo/demo_func',
            grpc__test_dot_proto_dot_proto__test__pb2.demo_request.SerializeToString,
            grpc__test_dot_proto_dot_proto__test__pb2.demo_reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
